import myimg from './Images/Eagle.jpg';
export const userData = [
    {
      name: 'Jan',
      "Active User": 4000,
    },
    {
        name: 'Feb',
        "Active User": 3000,
      },
      {
        name: 'Mar',
        "Active User": 5000,
      },
      {
        name: 'Apr',
        "Active User": 4000,
      },
      {
        name: 'May',
        "Active User": 3000,
      },
      {
        name: 'Jun',
        "Active User": 2000,
      },
      {
        name: 'Jul',
        "Active User": 4000,
      },
      {
        name: 'Aug',
        "Active User": 3000,
      },
      {
        name: 'Sept',
        "Active User": 1000,
      },
      {
        name: 'Oct',
        "Active User": 4000,
      },
      {
        name: 'Nov',
        "Active User": 3000,
      },
      {
        name: 'Dec',
        "Active User": 4000,
      },
  ];

  export const productData = [
    {
      name: "Jan",
      "Sales": 4000,
    },
    {
      name: "Feb",
      "Sales": 3000,
    },
    {
      name: "Mar",
      "Sales": 5000,
    },
  ];


  export const rows = [
    { id: 1, 
    name:'Apple Airpodes', 
    img:myimg, 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 2, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 3, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 4, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 5, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 6, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 7, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 8, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
   { id: 9, 
    name:'Apple Airpodes', 
    img:myimg , 
    stock:123,
    status:"active",
    price:"$120",
   },
  ];
